#pragma config(Sensor, in1,    armp,           sensorPotentiometer)
#pragma config(Sensor, in2,    dial,           sensorPotentiometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in4,    acc,            sensorAccelerometer)
#pragma config(Sensor, dgtl1,  pnintake,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  pnsky,          sensorDigitalOut)
#pragma config(Motor,  port2,           BL,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ML,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FL,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BR,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           MR,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           FR,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftArm,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "functions.c"



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous
//
//	1st position: Blue Cube score
int firstPos = 600;
//	2nd position: Blue Skyrise score
int secondPos = 1000;
//	3rd position: Red Cube score
int thirdPos = 1520;
//	4th position: Red Skyrise score
int fourthPos = 2250;
//  5th position: Raise Arm
int fifthPos = 3000;
//
//
/////////////////////////////////////////////////////////////////////////////////////////






//---------------------------------Variables-------------------------------------------//

//Height in which to be at to obtain a
int skyriseHeight = 1950;
int l=30;
int h=118;

//-------------------------------------------------------------------------------------//




void autonomous()  //Programs are chosen by the value of the dial potentiometer.
{
	//DO NOT COPY THE TOP!!!

	int position=SensorValue[dial];
	//11111111111111111111111111111111111111111111111111111111111111111111111111
	//Blue side block || Put block on post turn around grab two and put them somewhere
	if (position>=firstPos&&position<secondPos)
	{
	}



	//2222222222222222222222222262222222222222222222222222222222222222222222222
	//Blue side skyrise
	else if (position>=secondPos&&position<thirdPos)
	{
	}


	//33333333333333333333333333333333333333333333333333333333333333333333333333
	//Red side cube
	else if(position>=thirdPos&&position<fourthPos)
	{
	}


	//444444444444444444444444444444444444444444444444444444444444444444444444444
	//Red side skyrise
	else if(position>=fourthPos&&position<fifthPos)
	{
	}


	//55555555555555555555555555555555555555555555555555555555555555
	//Raise arm up
	else if(position>=fifthPos)
	{
	}
}


task main()
{
	//motor[leftArm]=118;
	//motor[rightArm]=118;
	///*
	//raiseArmSeconds(1);
	//lowerArmSeconds(1);
	for(int i=0;i<100;i++)
	{
		closesky();
		closeintake();
		wait(1);
		opensky();
		openintake();
		wait(1);
	}
	//*/
}
