#pragma config(Sensor, in1,    armp,           sensorPotentiometer)
#pragma config(Sensor, in2,    dial,           sensorPotentiometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  armUltra,       sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  intakeLimit,    sensorTouch)
#pragma config(Sensor, dgtl8,  pnr,            sensorDigitalIn)
#pragma config(Sensor, dgtl9,  pnl,            sensorDigitalIn)
#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightArm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftintake,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightintake,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "functions.c"



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous
//
//	1st position: Blue Cube score
int firstPos = 600;
//	2nd position: Blue Skyrise score
int secondPos = 1000;
//	3rd position: Red Cube score
int thirdPos = 1520;
//	4th position: Red Skyrise score
int fourthPos = 2250;
//  5th position: Raise Arm
int fifthPos = 3000;
//
//
/////////////////////////////////////////////////////////////////////////////////////////






//---------------------------------Variables-------------------------------------------//

//Height in which to be at to obtain a
int skyriseHeight = 1950;
int l=30;
int h=118;

//-------------------------------------------------------------------------------------//




void autonomous()  //Programs are chosen by the value of the dial potentiometer.
{
	//DO NOT COPY THE TOP!!!

	int position=SensorValue[dial];
	SensorValue(encoderLeft)=0;
	//startTask(armcontrol);
	/*SensorType[in3]=sensorNone;
	wait1Msec(1000);
	SensorType[in3]=sensorGyro;
	wait1Msec(2000);
	*/
	//11111111111111111111111111111111111111111111111111111111111111111111111111
	//Blue side block || Put block on post turn around grab two and put them somewhere
	if (position>=firstPos&&position<secondPos)
	{
		/*11 POINTS
		fancyTurnLeftDegrees(27,false,50);
		backwardTicks(60,50);
		wait(.3);
		raiseArmTicks(1950);
		lowerIntakeSeconds(1);
		fancyTurnRightDegrees(27,false,50);
		lowerArmSeconds(1);
		//First Cube
		turnLeftDegrees(20,50);
		fancyTurnLeftDegrees(52,50);
		forwardTicks(150,50);
		wait(.3);
		raiseIntakeSeconds(1.4);
		//Second Cube
		forwardTicks(400,50);
		fancyTurnLeftDegrees(33,false,50);
		backwardTicks(50,50);
		fancyTurnLeftDegrees(37,false,50);
		forwardTicks(60,50);
		wait(.6);
		raiseIntakeSeconds(1.2);
		//Onto Post
		turnRightDegrees(19,50);
		raiseArmTicks(1850);
		wait(.3);
		forwardTicks(50,50);
		lowerArmSeconds(.1);
		lowerIntakeSeconds(2);
		backwardTicks(30);
		*/

		//WORKING AUTO
		//wait(6.5);
		forwardTicks(130,118);
		raiseIntakeSeconds(.8);
		forwardTicks(50,118);
		turnRightDegrees(15);
		backwardTicks(100,118);
		turnRightDegrees(10);
		backwardTicks(100,118);
		turnRightDegrees(5.5);

		/*
		//Onto skyrise
		backwardTicks(100,118);
		raiseArmTicks(skyriseHeight);
		forwardTicks(85,118);
		lowerArmTicks(1700);
		lowerIntakeSeconds(2);
		backwardSeconds(.3);
		*/

		//Onto Post
		///*
		turnRightDegrees(60);
		backwardTicks(100);
		turnRightDegrees(30);
		backwardTicks(200);
		raiseArmTicks(2950);
		forwardTicks(310);
		lowerArmSeconds(.2);
		lowerIntakeSeconds(1.5);
		backwardSeconds(.4);
		//*/
	}


	//2222222222222222222222222222222222222222222222222222222222222222222222222
	//Blue side skyrise
	else if (position>=secondPos&&position<thirdPos)
	{

		turnRightDegrees(15,50);
		lowerIntakeSeconds(.5);
		fancyTurnRightDegrees(25,false,50);
		raiseArmTicks(skyriseHeight);
		fancyTurnLeftDegrees(37,true,50);
		lowerArmSeconds(1);
		raiseArmTicks(2100);
		fancyTurnLeftDegrees(40,false,50);
		fancyTurnRightDegrees(39,true,50);
		forwardTicks(7,50);
		lowerArmSeconds(1.2);
		raiseArmTicks(skyriseHeight);
		/*
		fancyTurnLeftDegrees(39.3,false,60);
		raiseArmTicks(skyriseHeight);
		forwardTicks(14,60);
		fullStop(10,70);
		wait1Msec(500);
		lowerArmSeconds(1);
		raiseArmSeconds(1);
		backwardTicks(100,118);
		turnRightDegrees(53,40);
		forwardTicks(48,60);
		fullStop(10);
		lowerArmSeconds(3);
		raiseArmTicks(1950);
		*/
	}


	//33333333333333333333333333333333333333333333333333333333333333333333333333
	//Red side cube
	else if(position>=thirdPos&&position<fourthPos)
	{
		forwardTicks(130,118);
		raiseIntakeSeconds(.8);
		forwardTicks(50,118);
		turnLeftDegrees(15);
		backwardTicks(100,118);
		turnLeftDegrees(10);
		backwardTicks(100,118);
		turnLeftDegrees(1.9,40);

		//Onto skyrise
		///*
		wait(4);
		backwardTicks(100,118);
		wait(.5);
		raiseArmTicks(skyriseHeight);
		wait(.5);
		forwardTicks(176,118);
		lowerArmTicks(1650);
		lowerIntakeSeconds(2);
		backwardSeconds(.3);
		//*/

		//Onto Post
		/*
		turnLeftDegrees(60);
		backwardTicks(100);
		turnLeftDegrees(67);
		backwardTicks(200);
		raiseArmTicks(2950);
		forwardTicks(310);
		lowerArmSeconds(.2);
		lowerIntakeSeconds(1.5);
		backwardSeconds(.4);
		*/
	}


	//444444444444444444444444444444444444444444444444444444444444444444444444444
	//Red side skyrise
	else if(position>=fourthPos&&position<fifthPos)
	{
	turnLeftDegrees(8,40);
	backwardTicks(100,118);
	raiseArmTicks(2000);
	forwardTicks(120,118);
	lowerArmSeconds(1);
	raiseArmTicks(2400);
	backwardTicks(100,118);
	turnLeftDegrees(40,80);
	forwardTicks(18,118);
	lowerArmSeconds(1.8);
	raiseArmSeconds(1);
	}


	//55555555555555555555555555555555555555555555555555555555555555
	//Raise arm up
	else if(position>=fifthPos)
	{
		//forwardTicks(100,118);
		//testing arms
		/*
		motor[leftArm]=118;
		motor[rightArm]=118;
		wait(.5);
		motor[leftArm]=0;
		motor[rightArm]=0;
		*/
	}
}


task main()
{
	autonomous();
}
