#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, in1,    armp,           sensorPotentiometer)
#pragma config(Sensor, in2,    dial,           sensorPotentiometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in4,    xAxis,          sensorAccelerometer)
#pragma config(Sensor, in5,    yAxis,          sensorAccelerometer)
#pragma config(Sensor, in6,    zAxis,          sensorAccelerometer)
#pragma config(Sensor, dgtl1,  pnintake,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  pnsky,          sensorDigitalOut)
#pragma config(Sensor, dgtl3,  skyUltra,       sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  rightUltra,     sensorNone)
#pragma config(Sensor, dgtl7,  leftUltra,      sensorNone)
#pragma config(Motor,  port2,           leftAdd,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           BL,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FL,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BR,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           rightAdd,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           FR,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftArm,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "functions.c"

int skyriseHeight = 1950;
int firstPos = 600;
int secondPos = 1000;
int thirdPos = 1520;
int fourthPos = 2250;
int fifthPos = 3000;


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Pre-Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////


void pre_auton()
{
/*
 bStopTasksBetweenModes = true;

 startTask(printGyroToLCD);
*/
}







/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous
//
//
//	1st position:Blue Cube score
//	2nd position:Blue Skyrise score
//	3rd position:Red Cube score
//	4th position:Red Skyrise score
//
//
/////////////////////////////////////////////////////////////////////////////////////////


task autonomous(){  //Programs are chosen by the value of the dial potentiometer.
		//DO NOT COPY THE TOP!!!


	int position=SensorValue[dial];
	//11111111111111111111111111111111111111111111111111111111111111111111111111
	//Blue side block || Put block on post turn around grab two and put them somewhere
	if (position>=firstPos&&position<secondPos)
	{
	}


	//2222222222222222222222222262222222222222222222222222222222222222222222222
	//Blue side skyrise
	else if (position>=secondPos&&position<thirdPos)
	{
	}


	//33333333333333333333333333333333333333333333333333333333333333333333333333
	//Red side cube
	else if(position>=thirdPos&&position<fourthPos)
	{
	}


	//444444444444444444444444444444444444444444444444444444444444444444444444444
	//Red side skyrise
	else if(position>=fourthPos&&position<fifthPos)
	{
	}


	//55555555555555555555555555555555555555555555555555555555555555
	//Raise arm up
	else if(position>=fifthPos)
	{
	}
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol(){
	bool half=false;
	int buttonToggleState8R = 0;//Skyrise
  int buttonPressed8R = 0;
  int buttonToggleState8D = 0;//Skyrise
  int buttonPressed8D = 0;
  int buttonToggleState7D = 0;//Intake
  int buttonPressed7D = 0;
	int buttonToggleState7L = 0;//Half Speed
  int buttonPressed7L = 0;

	//startTask(armcontrol);
	while (true) {
		if(bVEXNETActive){

			//Toggle intake---------------------------------------------------------------
			if( vexRT[ Btn7L ] == 1 ) {
	      if( ! buttonPressed7L ) {

	      	// change the toggle state
	      	buttonToggleState7L = 1 - buttonToggleState7L;

	        // Note the button is pressed
	        buttonPressed7L = 1;
	      }
	  	} else {

		    // the button is not pressed
		    buttonPressed7L = 0;
		  }

		  // Now do something with our toggle flag
	    if( buttonToggleState7L )
	    {
	      half=true;
	    }
	    else
	    {
	      half=false;
		  }

			//Toggle intake---------------------------------------------------------------
			if( vexRT[ Btn8D ] == 1 ) {
	      if( ! buttonPressed8D ) {

	      	// change the toggle state
	      	buttonToggleState8D = 1 - buttonToggleState8D;

	        // Note the button is pressed
	        buttonPressed8D = 1;
	      }
	  	} else {

		    // the button is not pressed
		    buttonPressed8D = 0;
		  }

		  // Now do something with our toggle flag
	    if( buttonToggleState8D )
	    {
	      closeintake();
	    }
	    else
	    {
	      openintake();
		  }

	   //Toggle skyrise------------------------------------------------
		  if( vexRT[ Btn7D ] == 1 )
	    {
	      if( ! buttonPressed7D )
	      {
	      	// change the toggle state
	      	buttonToggleState7D = 1 - buttonToggleState7D;

	        // Note the button is pressed
	        buttonPressed7D = 1;
	      }
	    }
	    else
	    {
		    // the button is not pressed
		    buttonPressed7D = 0;
		  }
	    // Now do something with our toggle flag
	    if( buttonToggleState7D )
	    {
	      closesky();
	    }
	    else
	    {
	      opensky();
		  }


			//DRIVE-----------------------------------------------------
			if (half==false){ //Check if drive toggles half speed.
				//give drive direct control.
				motor[BR] = vexRT[Ch2];
				motor[FR] = vexRT[Ch2];
				//motor[MR] = vexRT[Ch2];
				motor[BL] = vexRT[Ch3];
				motor[FL] = vexRT[Ch3];
				//motor[ML] = vexRT[Ch3];
			} else if(half ==true) {
				//give drive control but all motor maxes are a third of their orignal max.
				motor[BR] = vexRT[Ch2]/3;
				motor[FR] = vexRT[Ch2]/3;
				//motor[MR] = vexRT[Ch2]/3;
				motor[BL] = vexRT[Ch3]/3;
				motor[FL] = vexRT[Ch3]/3;
				//motor[ML] = vexRT[Ch3]/3;
			}


	  	//ARM MOTION----------------------------
			if(vexRT[Btn5D] == true)
			{
        	motor[rightArm] = -126;
        	motor[leftArm] = -126;
        	motor[rightAdd] = -126;
        	motor[leftAdd] = -126;
    	}
    	else if(vexRT[Btn6D] == true)
    	{
        	motor[rightArm] = 126;
        	motor[leftArm] = 126;
        	motor[rightAdd] = 126;
        	motor[leftAdd] = 126;
    	}
    	else
    	{
      	motor[rightArm] = 0;
      	motor[leftArm] = 0;
      	motor[rightAdd] = 0;
       	motor[leftAdd] = 0;
    	}
			wait1Msec(10);
		}
	}
}
