#pragma config(Sensor, in1,    armp,           sensorPotentiometer)
#pragma config(Sensor, in2,    dial,           sensorPotentiometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  pnsky,          sensorDigitalOut)
#pragma config(Sensor, dgtl6,  armultra,       sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  intakeLimit,    sensorTouch)
#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightArm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftintake,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightintake,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "functions.c"

int skyriseHeight = 1950;
int firstPos = 600;
int secondPos = 1000;
int thirdPos = 1520;
int fourthPos = 2250;
int fifthPos = 3000;

int heights[50];

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Pre-Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
 bStopTasksBetweenModes = true;

 startTask(printGyroToLCD);
}







/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous
//
//
//	1st position:Blue Cube score
//	2nd position:Blue Skyrise score
//	3rd position:Red Cube score
//	4th position:Red Skyrise score
//
//
/////////////////////////////////////////////////////////////////////////////////////////


task autonomous(){  //Programs are chosen by the value of the dial potentiometer.
		//DO NOT COPY THE TOP!!!

	int position=SensorValue[dial];
	SensorValue(encoderLeft)=0;
	//11111111111111111111111111111111111111111111111111111111111111111111111111
	//Blue side block || Put block on post turn around grab two and put them somewhere
	if (position>=firstPos&&position<secondPos)
	{
		//Onto skyrise
		/*
		//wait(1.1);
		forwardTicks(10,50);
		forwardTicks(130,118);
		raiseIntake();//Pick up cube
		forwardTicks(250,118);
		turnRightDegrees(35,50);
		backwardTicks(210,50);
		fancyTurnLeftDegrees(52.5,false,50);
		//backwardTicks(130,50);
		raiseArmTicks(1850);
		forwardTicks(1,50);
		//lowerArmSeconds(.2);
		lowerIntakeSeconds(2);
		wait(.3);
		//*/

		//Onto Post
		///*
		forwardTicks(130,50);
		raiseIntake();//Pick up cube
		forwardTicks(300,50);
		fancyTurnRightDegrees(30,false,50);
		backwardTicks(100,50);
		wait(.3);
		raiseArmTicks(2700);
		wait(.3);
		forwardTicks(65,50);
		wait(.3);
		//lowerArmSeconds(.1);
		lowerIntakeSeconds(2);
		backwardTicks(100);
		//*/
	}


	//2222222222222222222222222262222222222222222222222222222222222222222222222
	//Blue side skyrise
	else if (position>=secondPos&&position<thirdPos)
	{

		turnRightDegrees(15,50);
		lowerIntakeSeconds(.5);
		fancyTurnRightDegrees(25,false,50);
		raiseArmTicks(skyriseHeight);
		fancyTurnLeftDegrees(31,true,50);
		lowerArmSeconds(1);
		raiseArmTicks(2100);
		fancyTurnLeftDegrees(40,false,50);
		fancyTurnRightDegrees(37,true,50);
		forwardTicks(2,50);
		lowerArmSeconds(1.5);
		raiseArmTicks(skyriseHeight);
		/*
		fancyTurnLeftDegrees(39.3,false,60);
		raiseArmTicks(skyriseHeight);
		forwardTicks(14,60);
		fullStop(10,70);
		wait1Msec(500);
		lowerArmSeconds(1);
		raiseArmSeconds(1);
		backwardTicks(100,118);
		turnRightDegrees(53,40);
		forwardTicks(48,60);
		fullStop(10);
		lowerArmSeconds(3);
		raiseArmTicks(1950);
		*/
	}


	//33333333333333333333333333333333333333333333333333333333333333333333333333
	//Red side cube
	else if(position>=thirdPos&&position<fourthPos)
	{
		//Onto skyrise
		///*
		//wait(1.1);
		forwardTicks(10,50);
		forwardTicks(130,118);
		raiseIntake();//Pick up cube
		forwardTicks(250,118);
		turnLeftDegrees(35,50);
		backwardTicks(210,50);
		fancyTurnRightDegrees(52.5,false,50);
		//backwardTicks(130,50);
		raiseArmTicks(1850);
		forwardTicks(1,50);
		//lowerArmSeconds(.2);
		lowerIntakeSeconds(2);
		wait(.3);
		//*/

		//Onto Post
		/*
		forwardTicks(130,50);
		raiseIntake();//Pick up cube
		forwardTicks(300,50);
		fancyTurnLeftDegrees(30,false,50);
		backwardTicks(100,50);
		wait(.3);
		raiseArmTicks(2700);
		wait(.3);
		forwardTicks(65,50);
		wait(.3);
		//lowerArmSeconds(.1);
		lowerIntakeSeconds(2);
		backwardTicks(100);
		//*/
	}


	//444444444444444444444444444444444444444444444444444444444444444444444444444
	//Red side skyrise
	else if(position>=fourthPos&&position<fifthPos)
	{
		turnLeftDegrees(15,50);
		lowerIntakeSeconds(.5);
		fancyTurnLeftDegrees(25,false,50);
		raiseArmTicks(skyriseHeight);
		fancyTurnRightDegrees(37,true,50);
		lowerArmSeconds(1);
		raiseArmTicks(2100);
		fancyTurnRightDegrees(44,false,50);
		fancyTurnLeftDegrees(46,true,50);
		forwardTicks(1,50);
		lowerArmSeconds(1);
		raiseArmTicks(skyriseHeight);
		fancyTurnLeftDegrees(30,false,100);
		/*
		fancyTurnRightDegrees(39.3,false,60);
		raiseArmTicks(skyriseHeight);
		forwardTicks(14,60);
		fullStop(10,70);
		wait1Msec(500);
		lowerArmSeconds(1);
		raiseArmSeconds(1);
		backwardTicks(100,118);
		turnLeftDegrees(53,40);
		forwardTicks(48,60);
		fullStop(10);
		lowerArmSeconds(3);
		raiseArmTicks(1950);
		*/
	}


	//55555555555555555555555555555555555555555555555555555555555555
	//Raise arm up
	else if(position>=fifthPos)
	{

	//Trigger the pneuamtic a lot.
		for (int i;i<1000;i++)
		{
			if (SensorValue[pnsky]==0)
			{
				SensorValue[pnsky]=1;
				wait(.01);
			}
			else if (SensorValue[pnsky]==1)
			{
				SensorValue[pnsky]=0;
				wait(.01 );
			}
		}


}
}




/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol(){
	bool half=false;
	int buttonToggleState8r = 0;//half speed
  int buttonPressed8r = 0;
	int buttonToggleState7l = 0;//pneumatics
  int buttonPressed7l = 0;

	//startTask(armcontrol);
	while (true) {
		if(bVEXNETActive){

			//Toggle half speed---------------------------------------------------------------
			if( vexRT[ Btn7L ] == 1 ) {
	      if( ! buttonPressed7l ) {

	      	// change the toggle state
	      	buttonToggleState7l = 1 - buttonToggleState7l;

	        // Note the button is pressed
	        buttonPressed7l = 1;
	      }
	  	} else {

		    // the button is not pressed
		    buttonPressed7l = 0;
		  }

		  // Now do something with our toggle flag
	    if( buttonToggleState7l ) {
	      half=true;
	    } else {
	      half=false;
		  }

	   //Toggle pneumatics------------------------------------------------
		  if( vexRT[ Btn8R ] == 1 )
	    {
	      if( ! buttonPressed8r )
	      {
	      	// change the toggle state
	      	buttonToggleState8r = 1 - buttonToggleState8r;

	        // Note the button is pressed
	        buttonPressed8r = 1;
	      }
	    }
	    else
	    {
		    // the button is not pressed
		    buttonPressed8r = 0;
		  }
	    // Now do something with our toggle flag
	    if( buttonToggleState8r )
	    {
	      SensorValue[pnsky]=1;
	    }
	    else
	    {
	      SensorValue[pnsky]=0;
		  }




			//DRIVE-----------------------------------------------------
			if (half==false){ //Check if drive toggles half speed.
				//give drive direct control.
				motor[BR] = vexRT[Ch2];
				motor[FR] = vexRT[Ch2];
				motor[BL] = vexRT[Ch3];
				motor[FL] = vexRT[Ch3];
			} else if(half ==true) {
				//give drive control but all motor maxes are a third of their orignal max.
				motor[BR] = vexRT[Ch2]/3;
				motor[FR] = vexRT[Ch2]/3;
				motor[BL] = vexRT[Ch3]/3;
				motor[FL] = vexRT[Ch3]/3;
			}


	  	//ARM MOTION----------------------------
			if(vexRT[Btn5D] == true){
      	/*if(nMotorEncoder(rightArm) > nMotorEncoder(leftArm)){
        	motor[rightArm] = 127/2;
        	motor[leftArm] = 127;
      	}else if(nMotorEncoder(rightArm) < nMotorEncoder(leftArm)){
        	motor[rightArm] = 127;
        	motor[leftArm] = 127/2;
      	}else{*/
        	motor[rightArm] = -126;
        	motor[leftArm] = -126;
      	//}
    	}else if(vexRT[Btn6D] == true){
      	/*if(nMotorEncoder(rightArm) > nMotorEncoder(leftArm)){
        	motor[rightArm] = -10;
        	motor[leftArm] = -20;
      	}else if(nMotorEncoder(rightArm) < nMotorEncoder(leftArm)){
        	motor[rightArm] = -20;
        	motor[leftArm] = -10;
      	}else{*/
        	motor[rightArm] = 126;
        	motor[leftArm] = 126;
      	//}
    	}else{
      	motor[rightArm] = 0;
      	motor[leftArm] = 0;
    	}

    	if(vexRT[Btn6U] == true){
      	 motor[rightintake] = 118;
      	 motor[leftintake] = 118;
    	}else if(vexRT[Btn5U] == true){
      	 motor[leftintake] = -118;
      	 motor[rightintake] = -118;
    	}else{
      	motor[rightintake] = 0;
      	motor[leftintake] = 0;
    	}
			wait1Msec(10);
		}
	}
}
