#pragma config(Sensor, in1,    armP,           sensorPotentiometer)
#pragma config(Sensor, dgtl1,  er,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  el,             sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  limitswitch,    sensorTouch)
#pragma config(Sensor, dgtl6,  pn,             sensorDigitalOut)
#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           TRarm,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           TLarm,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           BRarm,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           BLarm,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Pre-Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
 bStopTasksBetweenModes = true;
}





/////////////////////////////////////////////////////////////////////////////////////////
//
//                                  Functions
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////




void clearmotor()
{
	motor[FR]=0;
	motor[FL]=0;
	motor[BR]=0;
	motor[BL]=0;
}


void turnr(float seconds)
{
	motor[FL]=118;
	motor[BL]=118;
	motor[FR]=-118;
	motor[BR]=-118;
	wait(seconds);
	clearmotor();
}
void turnl(float seconds)
{
	motor[FL]=-118;
	motor[BL]=-118;
	motor[FR]=118;
	motor[BR]=118;
	wait(seconds);
	clearmotor();
}




void forward(int ticks) //s is encoder ticks for wheels, can be right or left as they should be the same.
{
		ticks=ticks+100;
		nMotorEncoder[el]=0;
    while(SensorValue(el)<ticks)
    {
      motor[FL]=118;
    	motor[FR]=118;
    	motor[BL]=118;
    	motor[BR]=118;
    }
  motor[FL]=0;
	motor[FR]=0;
	motor[BL]=0;
	motor[BR]=0;
}

void backward(int ticks)
{
		ticks=ticks+100;
    nMotorEncoder[el] = 0;
    int enctick=SensorValue(el);
    while(enctick>-ticks)
    {
    motor[FL]=-118;
		motor[FR]=-118;
		motor[BL]=-118;
		motor[BR]=-118;
    }
	motor[FL]=0;
	motor[FR]=0;
	motor[BL]=0;
	motor[BR]=0;
}


//need to calculate how many ticks it is per degree turn.
void correctturn(int degrees) //add sensor ticks per degrees
{
	//CONVERT DEGREES TO TICKS!!!
		int ticks=degrees*3.44;
    int i=SensorValue( el );//named encoder

    //CHANGE THE 1 LATERRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
    if(1<180)
    {
        while (i < ticks)
        {
            motor[FL]=118;
            motor[BL]=118;
            motor[FR]=-118;
            motor[BR]=-118; //<- need to check how long is 1 tick.
        }
    }
    else
    {
        //subtract amount of ticks in 180 degrees
        int ticks= 1-ticks;
        while (i < ticks)
        {
            motor[FL]=-118;
            motor[BL]=-118;
            motor[FR]=118;
            motor[BR]=118;
        }
    }
}

void raisearm(int ticks)
{
	SensorValue[pn] = 0;//release
	while(SensorValue[armP]<ticks)
	{
		motor[TLarm]=118;
		motor[TRarm]=118;
		motor[BLarm]=118;
		motor[BRarm]=118;
	}
	motor[TLarm]=0;
	motor[TRarm]=0;
	motor[BLarm]=0;
	motor[BRarm]=0;
	SensorValue[pn] = 1;//lock
}

void lowerarm(float seconds)
{
			SensorValue[pn]=0;
      motor[TRarm]= -118;
			motor[TLarm]= -118;
			motor[BRarm]= -118;
			motor[BLarm]= -118;
   		wait(seconds);
    	motor[TRarm]= -0;
			motor[TLarm]= -0;
			motor[BRarm]= -0;
			motor[BLarm]= -0;
			SensorValue[pn]=1;
}


/*
void lowerarm(int ticks)
{
	while(sensorValue[armP]>ticks)
	{
		motor[TLarm]=-118;
		motor[TRarm]=-118;
		motor[BLarm]=-118;
		motor[BRarm]=-118;
	}
	motor[TLarm]=0;
	motor[TRarm]=0;
	motor[BLarm]=0;
	motor[BRarm]=0;
}
*/

void increment(int lev) //raising the arm to certain levels
{
		int level[]={1322,1685,1965,2235,2615,3030,1270};
    if(SensorValue[armP]<level[lev])
    {
        raisearm(level[lev]);
    }
}

void taketower()
{
				int level[]={1322,1685,1965,2235,2615,3030,1270};
        backward();
        increment(level[6]);
        forward();
        backward();
}


void drive(bool half)
{
		if (half==false)
		{
			motor[BR] = vexRT[Ch2];
			motor[FR] = vexRT[Ch2];
			motor[BL] = vexRT[Ch3];
			motor[FL] = vexRT[Ch3];
		}
		else if(half ==true)
		{
			motor[BR] = vexRT[Ch2]/3;
			motor[FR] = vexRT[Ch2]/3;
			motor[BL] = vexRT[Ch3]/3;
			motor[FL] = vexRT[Ch3]/3;
		}
}

void lock()
{
	SensorValue[pn]=1;
}
void release()
{
	SensorValue[pn]=0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////


task autonomous()
{
/*
	//autonomous for knocking cube
	motor[TRarm]=118;
	motor[TLarm]=118;
	motor[BRarm]=118;
	motor[BLarm]=118;
	wait(1);
	motor[TRarm]=0;
	motor[TLarm]=0;
	motor[BRarm]=0;
	motor[BLarm]=0;
	motor[FL]=118;
	motor[BL]=118;
	motor[FR]=118;
	motor[BR]=118;
	wait(1);
	motor[FL]=0;
	motor[BL]=0;
	motor[FR]=0;
	motor[BR]=0;
		*/




			//AUTONOMOUS FOR SCORING CUBE ON THE RED SIDE
			SensorValue[pn]=0;
        increment(4);
        wait(.3);
        turnl(.4);
       	motor[FL]=-118;
	    	motor[FR]=-118;
	    	motor[BL]=-118;
	    	motor[BR]=-118;
	    	wait(.4);
	    	motor[FL]=0;
	    	motor[FR]=0;
	    	motor[BL]=0;
	    	motor[BR]=0;
	      lowerarm(.3);
        turnl(.5);

		//AUTONOMOUS FOR SCORING CUBE ON THE BLUE SIDE
    	/*	SensorValue[pn]=0;
        increment(4);
        wait(.3);
        turnr(.25);

       	motor[FL]=-118;
	    	motor[FR]=-118;
	    	motor[BL]=-118;
	    	motor[BR]=-118;
	    	wait(.4);
	    	motor[FL]=0;
	    	motor[FR]=0;
	    	motor[BL]=0;
	    	motor[BR]=0;
	      lowerarm(.3);
        turnl(.5);
       //*/
     //Autonomous for blue skyrise
      /*
      motor[FL]=-118;
    	motor[FR]=-118;
    	motor[BL]=-118;
    	motor[BR]=-118;
    	wait(.35);
    	motor[FL]=0;
    	motor[FR]=0;
    	motor[BL]=0;
    	motor[BR]=0;
      increment(6);
      motor[FL]=118;
    	motor[FR]=118;
    	motor[BL]=118;
    	motor[BR]=118;
    	wait(1);
    	motor[FL]=0;
    	motor[FR]=0;
    	motor[BL]=0;
    	motor[BR]=0;
    	increment(3);
    	motor[FL]=-118;
    	motor[FR]=-118;
    	motor[BL]=-118;
    	motor[BR]=-118;
    	wait(.5);
    	motor[FL]=0;
    	motor[FR]=0;
    	motor[BL]=0;
    	motor[BR]=0;






       /*
        for(int i=1;i<7;i++)
        {
            //correctturn(90);
    				turnl(1.5);
            taketower();
            increment(i);
            //correctturn(270);
            turnr(1.5);
            lowerarm(.5);
            backward(105);
        }


			increment(6);
			forward(1);
			increment (4);
			backward(1);
			turnr(.4);
			lowerarm(.5);
			*/
}





/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	bool half=false;
	int buttonToggleState8r = 0;
  int buttonPressed8r = 0;
	int buttonToggleState7l = 0;
  int buttonPressed7l = 0;
	while (true)
{



		if( vexRT[ Btn7L ] == 1 )
  {
      if( ! buttonPressed7l )
      {
      	// change the toggle state
      	buttonToggleState7l = 1 - buttonToggleState7l;

        // Note the button is pressed
        buttonPressed7l = 1;
      }
  }
  else
  {
	  // the button is not pressed
	   buttonPressed7l = 0;
	}


  // Now do something with our toggle flag
  if( buttonToggleState7l )
  {
      half=true;
  }
  else
  {
      half=false;
	}





	if( vexRT[ Btn8R ] == 1 )
  {
      if( ! buttonPressed8r )
      {
      	// change the toggle state
      	buttonToggleState8r = 1 - buttonToggleState8r;

        // Note the button is pressed
        buttonPressed8r = 1;
      }
  }
  else
  {
	  // the button is not pressed
	   buttonPressed8r = 0;
	}


  // Now do something with our toggle flag
  if( buttonToggleState8r )
  {
      lock();
  }
  else
  {
      release();
	}











		drive(half);
		motor[TRarm] = 0;
  	motor[TLarm] = 0;
  	motor[BRarm] = 0;
  	motor[BLarm] = 0;

		while(vexRT[Btn6D] == 1)
		{
			motor[TRarm] = 118;
  		motor[TLarm] = 118;
  		motor[BRarm] = 118;
  		motor[BLarm] = 118;
  		drive(half);
		}

		while(vexRT[Btn5D] == 1)
		{
			motor[TRarm] = -118;
  		motor[TLarm] = -118;
  		motor[BRarm] = -118;
  		motor[BLarm] = -118;
  		drive(half);
		}

		while(vexRT[Btn6U] == 1)
		{
			motor[TRarm] = 118/2;
  		motor[TLarm] = 118/2;
  		motor[BRarm] = 118/2;
  		motor[BLarm] = 118/2;
  		drive(half);
		}
		while(vexRT[Btn5U] == 1)
		{
			motor[TRarm] = -118/2;
  		motor[TLarm] = -118/2;
  		motor[BRarm] = -118/2;
  		motor[BLarm] = -118/2;
  		drive(half);
		}
	}
}




















//Hard coded autonomous

/*
task autonomous()
{
	while(true)
	{
		if(SensorValue[limitswitch] == 1)
		{
			break;
		}
	}
	while(SensorValue[armP] <= 1270)
	{
			motor[TRarm]= 118;
			motor[TLarm]= 118;
			motor[BRarm]= 118;
			motor[BLarm]= 118;
	}
	motor[TRarm]= 0;
	motor[TLarm]= 0;
	motor[BRarm]= 0;
	motor[BLarm]= 0;
	SensorValue[f] = 1;

	motor[FL]=118;
  motor[FR]=118;
	motor[BL]=118;
  motor[BR]=118;
  wait10Msec(1000);

  SensorValue[pn] = 0;
  while(SensorValue[armP] <= 1400)
  {
	 	motor[TRarm]= 118;
		motor[TLarm]= 118;
		motor[BRarm]= 118;
		motor[BLarm]= 118;
	}
	motor[TRarm]= 0;
	motor[TLarm]= 0;
	motor[BRarm]= 0;
	motor[BLarm]= 0;
	SensorValue[pn] = 1;

	motor[FL]=-90;
  motor[FR]=-90;
	motor[BL]=-90;
  motor[BR]=-90;
  wait10Msec(1000);

  motor[FL]=0;
  motor[FR]=0;
	motor[BL]=0;
  motor[BR]=0;
  wait10Msec(2000);

  SensorValue[pn] = 0;
	motor[TRarm]= -118;
	motor[TLarm]= -118;
	motor[BRarm]= -118;
	motor[BLarm]= -118;
	wait10Msec(1000);

	motor[TRarm]= 0;
	motor[TLarm]= 0;
	motor[BRarm]= 0;
	motor[BLarm]= 0;

	while(true)
	{
		if(SensorValue[limitswitch] == 1)
		{
			break;
		}
	}
	while(SensorValue[armP] <= 1270)
	{
			motor[TRarm]= 118;
			motor[TLarm]= 118;
			motor[BRarm]= 118;
			motor[BLarm]= 118;
	}
	motor[TRarm]= 0;
	motor[TLarm]= 0;
	motor[BRarm]= 0;
	motor[BLarm]= 0;
	SensorValue[pn] = 1;

	motor[FL]=118;
  motor[FR]=118;
	motor[BL]=118;
  motor[BR]=118;
  wait10Msec(1000);

  SensorValue[pn] = 0;
  while(SensorValue[armP] <= 1750)
  {
	 	motor[TRarm]= 118;
		motor[TLarm]= 118;
		motor[BRarm]= 118;
		motor[BLarm]= 118;
	}
	motor[TRarm]= 0;
	motor[TLarm]= 0;
	motor[BRarm]= 0;
	motor[BLarm]= 0;
	SensorValue[pn] = 1;

	motor[FL]=-90;
  motor[FR]=-90;
	motor[BL]=-90;
  motor[BR]=-90;
  wait10Msec(1000);

  motor[FL]=0;
  motor[FR]=0;
	motor[BL]=0;
  motor[BR]=0;
  wait10Msec(2000);

  SensorValue[pn] = 0;
	motor[TRarm]= -118;
	motor[TLarm]= -118;
	motor[BRarm]= -118;
	motor[BLarm]= -118;
	wait10Msec(1000);

	motor[TRarm]= 0;
	motor[TLarm]= 0;
	motor[BRarm]= 0;
	motor[BLarm]= 0;
	wait10Msec(2000);
}

*/
