/*
	***************************************************
	This file will always be a working copy of the code
	***************************************************
*/

#pragma config(I2C_Usage, I2C1, i2cSensors)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"

void pre_auton(){
	bStopTasksBetweenModes = true;
}

task autonomous(){

}

task usercontrol(){

}
