#pragma config(Sensor, in1,    armpr,          sensorPotentiometer)
#pragma config(Sensor, in2,    armpl,          sensorPotentiometer)
#pragma config(Sensor, in3,    dial,           sensorPotentiometer)
#pragma config(Sensor, dgtl1,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  pn,             sensorDigitalIn)
#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftintake,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightintake,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

    motor[FL]=118;
		wait(5);
		motor[FL]=0;
		motor[BL]=118;
		wait(5);
		motor[BL]=0;
		motor[FR]=118;
		wait(5);
		motor[FR]=0;
		motor[BR]=118;
		wait(5);
		motor[BR]=0;

}
