#pragma config(Sensor, dgtl2,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl4,  touchIt,        sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
			clearLCDLine(0);
			displayNextLCDString("Sonar: ");
			displayNextLCDNumber(SensorValue[sonarSensor]);

			if(SensorValue[touchIt] == 1){
				break;
			}

			wait10Msec(1);
	}
}
